services:

  db-data:
    image: busybox
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["true"]

  db:
    image: postgres:15
    container_name: proyecto-db
    environment:
      POSTGRES_DB: proyecto
      POSTGRES_USER: proyecto
      POSTGRES_PASSWORD: proyecto
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - proyecto-net

  web:
    build: .
    image: ghcr.io/lorena47/matchgricola-web:latest
    container_name: proyecto-web
    depends_on:
      - db
    environment:
      POSTGRES_DB: proyecto
      POSTGRES_USER: proyecto
      POSTGRES_PASSWORD: proyecto
      DB_HOST: db
      DB_PORT: 5432
      USE_POSTGRES: "True"
      DEBUG: "True"
      SECRET_KEY: "dev-secret-key"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
    ports:
      - "8000:8000"
    networks:
      - proyecto-net
    volumes:
      - staticfiles:/app/staticfiles

volumes:
  pgdata: {}
  staticfiles: {}

networks:
  proyecto-net: {}
